export interface Recipe {
  slug: string;
  title: string;
  emoji: string;
  time: string;
  tags: string[];
  description: string;
  steps: string[];
  gradient: string;
}

export const RECIPES: Recipe[] = [
  {
    slug: "honey-oat-bowl",
    title: "Honey Oat Bowl",
    emoji: "🥣",
    time: "10 min",
    tags: ["cozy", "homemade"],
    description: "Warm oats with honey and a pinch of cinnamon.",
    steps: ["Simmer oats in milk.", "Stir in honey.", "Top with fruit if you like."],
    gradient: "from-amber-100 to-cream",
  },
  {
    slug: "lavender-latte",
    title: "Lavender Latte",
    emoji: "☕",
    time: "8 min",
    tags: ["cafe", "dreamy"],
    description: "Soft floral notes in steamed milk.",
    steps: ["Brew espresso or strong coffee.", "Warm milk with a drop of lavender syrup.", "Pour slowly."],
    gradient: "from-lavender-100 to-cream",
  },
  {
    slug: "tomato-soup",
    title: "Creamy Tomato Soup",
    emoji: "🍅",
    time: "25 min",
    tags: ["comfort", "homemade"],
    description: "Like a hug in a bowl.",
    steps: ["Sauté onion.", "Add tomatoes and broth.", "Blend until silky."],
    gradient: "from-rose-100 to-cream",
  },
  {
    slug: "avocado-toast",
    title: "Soft Avocado Toast",
    emoji: "🥑",
    time: "7 min",
    tags: ["healthy", "quick"],
    description: "Smashed avocado on sourdough.",
    steps: ["Toast bread.", "Mash avocado with salt.", "Add chili flakes if brave."],
    gradient: "from-green-100 to-cream",
  },
  {
    slug: "banana-pancakes",
    title: "Banana Pancakes",
    emoji: "🥞",
    time: "15 min",
    tags: ["comfort", "weekend"],
    description: "Fluffy and barely sweet.",
    steps: ["Mash banana into batter.", "Cook on low heat.", "Serve with maple."],
    gradient: "from-yellow-100 to-cream",
  },
  {
    slug: "miso-soup",
    title: "Quiet Miso Soup",
    emoji: "🍲",
    time: "12 min",
    tags: ["healthy", "cozy"],
    description: "Gentle umami for slow evenings.",
    steps: ["Heat dashi or broth.", "Dissolve miso off heat.", "Add tofu and greens."],
    gradient: "from-stone-100 to-cream",
  },
  {
    slug: "berry-smoothie",
    title: "Berry Cloud Smoothie",
    emoji: "🫐",
    time: "5 min",
    tags: ["healthy", "quick"],
    description: "Frozen berries and yogurt.",
    steps: ["Blend berries.", "Add yogurt.", "Sip slowly."],
    gradient: "from-purple-100 to-cream",
  },
  {
    slug: "grilled-cheese",
    title: "Grilled Cheese",
    emoji: "🧀",
    time: "10 min",
    tags: ["comfort", "fast"],
    description: "Crispy outside, melty inside.",
    steps: ["Butter bread.", "Add cheese.", "Cook low and slow."],
    gradient: "from-orange-100 to-cream",
  },
  {
    slug: "chai-porridge",
    title: "Chai Porridge",
    emoji: "🫖",
    time: "12 min",
    tags: ["cozy", "spiced"],
    description: "Oats steeped with chai spices.",
    steps: ["Warm milk with spices.", "Add oats.", "Sweeten lightly."],
    gradient: "from-amber-50 to-cream",
  },
  {
    slug: "cucumber-salad",
    title: "Cucumber Ribbon Salad",
    emoji: "🥒",
    time: "8 min",
    tags: ["healthy", "light"],
    description: "Cool and crisp.",
    steps: ["Ribbon cucumber.", "Dress with rice vinegar.", "Top with sesame."],
    gradient: "from-emerald-50 to-cream",
  },
  {
    slug: "dark-chocolate-mug",
    title: "Dark Chocolate Mug Cake",
    emoji: "🍫",
    time: "6 min",
    tags: ["treat", "comfort"],
    description: "A tiny dessert ritual.",
    steps: ["Mix dry ingredients in mug.", "Add milk and oil.", "Microwave 90 seconds."],
    gradient: "from-stone-200 to-cream",
  },
  {
    slug: "egg-rice-bowl",
    title: "Soft Egg Rice Bowl",
    emoji: "🍳",
    time: "14 min",
    tags: ["protein", "homemade"],
    description: "Rice, egg, soy, scallions.",
    steps: ["Cook rice.", "Fry egg gently.", "Assemble with soy and oil."],
    gradient: "from-yellow-50 to-cream",
  },
  {
    slug: "roasted-carrots",
    title: "Honey Roasted Carrots",
    emoji: "🥕",
    time: "30 min",
    tags: ["healthy", "side"],
    description: "Caramel edges, soft centers.",
    steps: ["Toss carrots in oil and honey.", "Roast at 200°C.", "Finish with salt."],
    gradient: "from-orange-50 to-cream",
  },
  {
    slug: "overnight-oats",
    title: "Overnight Oats",
    emoji: "🫙",
    time: "5 min prep",
    tags: ["quick", "healthy"],
    description: "Ready when you wake.",
    steps: ["Mix oats and milk in jar.", "Refrigerate overnight.", "Add toppings in morning."],
    gradient: "from-blue-50 to-cream",
  },
  {
    slug: "herb-pasta",
    title: "Herb Butter Pasta",
    emoji: "🍝",
    time: "18 min",
    tags: ["comfort", "easy"],
    description: "Simple pasta with fresh herbs.",
    steps: ["Boil pasta.", "Melt butter with herbs.", "Toss together."],
    gradient: "from-green-50 to-cream",
  },
  {
    slug: "matcha-latte",
    title: "Home Matcha",
    emoji: "🍵",
    time: "6 min",
    tags: ["cafe", "calm"],
    description: "Whisked matcha with oat milk.",
    steps: ["Sift matcha.", "Whisk with warm water.", "Add steamed oat milk."],
    gradient: "from-emerald-100 to-cream",
  },
  {
    slug: "apple-cinnamon",
    title: "Baked Apple Cinnamon",
    emoji: "🍎",
    time: "22 min",
    tags: ["cozy", "treat"],
    description: "Warm apples with cinnamon.",
    steps: ["Core apples.", "Fill with cinnamon and butter.", "Bake until soft."],
    gradient: "from-red-50 to-cream",
  },
  {
    slug: "tahini-toast",
    title: "Tahini Banana Toast",
    emoji: "🍌",
    time: "5 min",
    tags: ["healthy", "quick"],
    description: "Nutty tahini meets sweet banana.",
    steps: ["Toast bread.", "Spread tahini.", "Top with banana slices."],
    gradient: "from-amber-50 to-cream",
  },
  {
    slug: "veggie-ramen",
    title: "Soft Veggie Ramen",
    emoji: "🍜",
    time: "20 min",
    tags: ["comfort", "warm"],
    description: "Quick broth with greens.",
    steps: ["Simmer broth.", "Cook noodles.", "Add veggies and egg if you like."],
    gradient: "from-orange-100 to-cream",
  },
  {
    slug: "yogurt-parfait",
    title: "Yogurt Parfait",
    emoji: "🥛",
    time: "5 min",
    tags: ["healthy", "layered"],
    description: "Yogurt, granola, fruit layers.",
    steps: ["Layer yogurt.", "Add granola.", "Top with fruit."],
    gradient: "from-pink-50 to-cream",
  },
];

export function getSundayRecipe(): Recipe {
  const week = Math.floor(Date.now() / (7 * 24 * 60 * 60 * 1000));
  return RECIPES[week % RECIPES.length];
}
