export interface WhisperEntry {
  key: string;
  text: string;
  trigger: "default" | "stormy" | "rainy" | "low_water" | "monday" | "shelf" | "quest_streak";
}

export const WHISPER_LIBRARY: WhisperEntry[] = [
  { key: "w01", text: "proud of you.", trigger: "default" },
  { key: "w02", text: "tiny progress still counts.", trigger: "default" },
  { key: "w03", text: "don't forget to rest.", trigger: "default" },
  { key: "w04", text: "you showed up today.", trigger: "default" },
  { key: "w05", text: "soft days are valid.", trigger: "default" },
  { key: "w06", text: "your pace is enough.", trigger: "default" },
  { key: "w07", text: "gentle with yourself.", trigger: "default" },
  { key: "w08", text: "this moment is yours.", trigger: "default" },
  { key: "w09", text: "you're doing fine.", trigger: "default" },
  { key: "w10", text: "small steps bloom.", trigger: "default" },
  { key: "w11", text: "rough days deserve softness too.", trigger: "stormy" },
  { key: "w12", text: "storms pass quietly.", trigger: "stormy" },
  { key: "w13", text: "you don't have to be bright.", trigger: "stormy" },
  { key: "w14", text: "rainy hearts need warmth.", trigger: "rainy" },
  { key: "w15", text: "cozy is allowed today.", trigger: "rainy" },
  { key: "w16", text: "a glass for you, slowly.", trigger: "low_water" },
  { key: "w17", text: "sip when you're ready.", trigger: "low_water" },
  { key: "w18", text: "a fresh week. no pressure.", trigger: "monday" },
  { key: "w19", text: "mondays can be soft.", trigger: "monday" },
  { key: "w20", text: "you've been growing quietly.", trigger: "shelf" },
  { key: "w21", text: "your memories are blooming.", trigger: "shelf" },
  { key: "w22", text: "three tiny wins today.", trigger: "quest_streak" },
  { key: "w23", text: "your garden noticed.", trigger: "quest_streak" },
  { key: "w24", text: "stillness is a kind of care.", trigger: "default" },
  { key: "w25", text: "you're allowed to pause.", trigger: "default" },
  { key: "w26", text: "nothing to prove today.", trigger: "default" },
  { key: "w27", text: "your effort is seen.", trigger: "default" },
  { key: "w28", text: "breathe. you're here.", trigger: "default" },
  { key: "w29", text: "kindness includes you.", trigger: "default" },
  { key: "w30", text: "today can be light.", trigger: "default" },
  { key: "w31", text: "you're not behind.", trigger: "default" },
  { key: "w32", text: "rest is productive too.", trigger: "default" },
  { key: "w33", text: "your room is growing.", trigger: "default" },
  { key: "w34", text: "petals for showing up.", trigger: "default" },
  { key: "w35", text: "slow is still forward.", trigger: "default" },
  { key: "w36", text: "you matter quietly.", trigger: "default" },
  { key: "w37", text: "no rush. just presence.", trigger: "default" },
  { key: "w38", text: "your softness is strength.", trigger: "default" },
  { key: "w39", text: "today asked little of you.", trigger: "default" },
  { key: "w40", text: "that's enough for now.", trigger: "default" },
  { key: "w41", text: "a quiet win is still a win.", trigger: "default" },
  { key: "w42", text: "you're tending yourself well.", trigger: "default" },
  { key: "w43", text: "evening can be gentle.", trigger: "default" },
  { key: "w44", text: "morning you did enough.", trigger: "default" },
  { key: "w45", text: "your check-in matters.", trigger: "default" },
  { key: "w46", text: "keep what's cozy.", trigger: "default" },
  { key: "w47", text: "you're blooming in your way.", trigger: "default" },
  { key: "w48", text: "no guilt. just presence.", trigger: "default" },
  { key: "w49", text: "your garden remembers.", trigger: "default" },
  { key: "w50", text: "softness suits you.", trigger: "default" },
  { key: "w51", text: "one breath at a time.", trigger: "default" },
  { key: "w52", text: "you chose care today.", trigger: "default" },
  { key: "w53", text: "that's a soft win.", trigger: "default" },
  { key: "w54", text: "your pace is beautiful.", trigger: "default" },
  { key: "w55", text: "you don't owe perfection.", trigger: "default" },
  { key: "w56", text: "cozy counts as progress.", trigger: "default" },
  { key: "w57", text: "you're allowed to be tired.", trigger: "default" },
  { key: "w58", text: "tomorrow can wait.", trigger: "default" },
  { key: "w59", text: "your note was enough.", trigger: "default" },
  { key: "w60", text: "gentle is the goal.", trigger: "default" },
  { key: "w61", text: "you're building a ritual.", trigger: "default" },
  { key: "w62", text: "this app is your room.", trigger: "default" },
  { key: "w63", text: "thanks for stopping by.", trigger: "default" },
  { key: "w64", text: "your water counts.", trigger: "low_water" },
  { key: "w65", text: "sleep when you can.", trigger: "default" },
  { key: "w66", text: "spending isn't shame.", trigger: "default" },
  { key: "w67", text: "treats are allowed.", trigger: "default" },
  { key: "w68", text: "you're not a project.", trigger: "default" },
  { key: "w69", text: "comfort is valid data.", trigger: "default" },
  { key: "w70", text: "your mood is weather.", trigger: "default" },
  { key: "w71", text: "clouds move. so can you.", trigger: "stormy" },
  { key: "w72", text: "golden hours come back.", trigger: "default" },
  { key: "w73", text: "dreamy days are real.", trigger: "default" },
  { key: "w74", text: "you're not alone here.", trigger: "default" },
  { key: "w75", text: "tiny quests, tiny blooms.", trigger: "quest_streak" },
  { key: "w76", text: "your shelf holds love.", trigger: "shelf" },
  { key: "w77", text: "no exclamation needed.", trigger: "default" },
  { key: "w78", text: "you're already enough.", trigger: "default" },
  { key: "w79", text: "keep the ritual soft.", trigger: "default" },
  { key: "w80", text: "see you tomorrow, gently.", trigger: "default" },
];
